### ISSUE TITLE
Light Entity not working (turn on/off)

### ISSUE THREAD

**Issue by ecointet** [agillis/esphome-modular-lvgl-buttons#14]
Everything is working well (display, system switch, etc...) but no way to get a light entity working. The status and button action are not working.
Anything I am missing to turn on/off an entity?

```
        - button: !include
            file: modules/buttons/light_button.yaml
            vars:
              uid: button_2
              height: $button_height_single
              text: Office Bed Light
              icon: $lightbulb
              entity_id: light.office_bed_switch_light_4
```
