### ISSUE TITLE
Give internal relays a name so that controllable from Home Assistant

### ISSUE THREAD

**Issue by dala318** [agillis/esphome-modular-lvgl-buttons#3]
First of all, great repo! I'm re-using as much as I can from it.

Since I have a bunch of other ESPHome devices I can't clone the repo to my config dir, but I am including specific files.
Now since I want to avoid copying files but instead full yours (and get all the latest updates without manually keep track and copy) I would like to propose an improvement.

Could you add a `name` to the light component so that the internal relay get visible and controllable from within Home Assistant?

https://github.com/agillis/esphome-modular-lvgl-buttons/blob/f4e13a5586342b0d60fa3726986a3115ff500d0d/modules/sensors/local_relay_button_state.yaml#L8-L10 

Also if you want, add some guide in the README to others how parts of the config can be included without cloning repo

Basic file include
```yaml
packages:
  hardware: github://agillis/esphome-modular-lvgl-buttons/modules/hardware/guition-esp32-s3-4848s040.yaml@main
```

With vars (should work but a bit buggy i my oppinion, EDIT: seem I'm a bit to early,  https://github.com/esphome/esphome/pull/7606 only on dev yet )
```yaml
packages:
  buttons
    url: https://github.com/agillis/esphome-modular-lvgl-buttons
    files:
      - name: /modules/sensors/local_relay_button_state.yaml
        vars:
          uid: button_1
          entity_id: internal_relay_1
    ref: main
```
