### ISSUE TITLE
waveshare-esp32-s3-touch-lcd-7-display_modular.yaml

### ISSUE THREAD

**Issue by weswark** [agillis/esphome-modular-lvgl-buttons#9]
Hi
"waveshare-esp32-s3-touch-lcd-7-display_modular.yaml" is looking for a core folder that does not exist. Is there a way to update this?

**Comment by agillis** [comment]
I updated my entire codebase to make it easier to use. You can now create a button like this

```
        - button: !include
            file: modules/buttons/dimmer_light_button.yaml
            vars:
              uid: button_4
              height: $button_height_double
              text: RGB light
              icon: $string_lights
              entity_id: light.athom_rgb_light_d93662_rgb_light_strip
```

I updated waveshare-esp32-s3-touch-lcd-7-display_modular.yam to use this new way to create buttons.
